### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Prodigitude**
Changes made for PHP7 compatibility to allow plugin installation.

### CODE REVIEW

**Comment by Prodigitude** [comment]
It installed and worked just fine on my server once I made these changes.

**Comment by collinkrawll** [comment]
Hi, thank you for the PR. We are actively testing the plugin against PHP 7 so the current version of the plugin should already work with it. Were you getting an error message? Can you post it? 

Also, if you could, please provide steps to reproduce the issue so that we can confirm that this PR fixes it. Thanks!

**Comment by Prodigitude** [comment]
Collin, it was trying to get it to recognize it for installation. If you
recall, I initially posted an issue several months ago trying to install
it. It would not install in my environment that was already running php7. I
thought maybe it was the mautic upgrade, but that was not it. I could not
get Mautic to install the bundle no matter how many times I cleared the
cache and tried other suggestions. I had this happen in both in my
development environment and my live server which both ran php7. You
suggested to me I try other plugins to see if they would install. I replied
that I had successfully installed others including a private one that I
developed for my main client. It didn't occur to me that this might be a
php 7 problem until the issue was closed and I went digging further.

I suspect that if you were upgrading your server from php5 to php7 and the
plugin was already installed, the current code would be completely
compatible for running. You could try a new Mautic installation in a php7
environment to see if your current plugin will install vs one with the
changes that I have made.

I actually implemented the fix a while back, so I can't paste the exact
error but I think it was about exception handling and I don't think they
appeared in the Mautic's errors. I think that I had to dig through the
server errors that coordinated with the moments that I tried to install. I
was just happy to get it to installed and go on to test the plugin for my
client's needs. I apologize for not issuing a pull request sooner while
this was fresher in my mind.

**Comment by collinkrawll** [comment]
Thanks for taking the time to work on this and share your solution. 

I test using [Mautic's Docker image](https://hub.docker.com/r/mautic/mautic/). So I spin up the docker container using the official image, I then install the plugin and then test it (both using PHPUnit and manually). The latest Mautic Docker image is on PHP 7 so I'm regularly testing the plugin with a brand new install on PHP 7.

Are you able to revise the pull request - right now it shows that you added [784 lines](https://github.com/thirdset/ThirdSetMauticTimingBundle/pull/12/files), however it seems that the vast majority of these lines are the same as they were previously. I'm not sure if this was a whitespace or line ending issue or maybe something with git/GitHub but if you can get it down to a couple of changes, then we can figure out whether they are safe and what effect the changes would have.

Here's how a PR would typically look: https://github.com/thirdset/ThirdSetMauticTimingBundle/pull/1/files

Thanks again.

**Comment by Prodigitude** [comment]
My apologies... I am less familiar with contributing on Git than I should
be. That was part of the delay in submitting since previously I was using
Google Code. You are correct, it is actually very few lines that were
changed but it shows both pages in their entirety. I will attempt to revise
in a few hours.

**Comment by collinkrawll** [comment]
If you could, please consolidate your changes as previously discussed and open a new PR. Thanks!

**Pull request closed without merging**
